const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHMENTS = "NEW_ATTACHMENTS";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
const CHAT_STARTED = "CHAT_STARTED";
const CHAT_ENDED = "CHAT_ENDED";
const ONLINE = "ONLINE";
export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENTS,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  CHAT_STARTED,
  CHAT_ENDED,
  ONLINE,
};
